### PR TITLE
Google books api

### LINKED ISSUE #7: Consume Google Books API
- [ ] Service
- [ ] Facades
- [ ] PORO with attributes (isbn, title, author, image_url (make sure to get biggest thumbnail), page_count, summary

### PR DESCRIPTION
**Pull request by Freeing3092**
Type of change

    [x] New feature
    [] Bug Fix

Implements/Fixes:

    - Closes #7 

Neccesary checkmarks:

    [x] All Tests are Passing
    [x] The code will run locally

Check the correct boxes

    [x] This broke nothing
    [] This broke some stuff
    [] This broke everything

Testing Changes

    [x] No Tests have been changed
    [] Some Tests have been changed
    [] All of the Tests have been changed(Please describe what in the world happened)

Checklist:

    [x] My code has no unused/commented out code
    [x] I have reviewed my code
    [] I have commented my code, particularly in hard-to-understand areas
    [x] I have fully tested my code

GIF ME

### CODE REVIEW

**Review by amikaross — APPROVED** [review]
Cool - I like that it's 'BookPoro' to differentiate from our books. We still need to figure out how we're going check for the existence of the book in our db once they select one (isbn?) but this looks great! Nice job.

**Comment by amikaross** [comment]
The other thing we need to decide about is how we're going to allow for calling / providing this data to the front end. We could use a restful endpoint and leave graphql for only our own resources or we could figure out how to feed the facade to graphql as an object type maybe?

**Review by naomiyocum — APPROVED** [review]
Looks good! If a user wants to search by just author or by just title though I think we would need to create separate methods?

**Comment by naomiyocum** [comment]
> The other thing we need to decide about is how we're going to allow for calling / providing this data to the front end. We could use a restful endpoint and leave graphql for only our own resources or we could figure out how to feed the facade to graphql as an object type maybe?

I think we could feed the Facade to GraphQL, since the Facade is returning an object hopefully it should work

**Review by naomiyocum — APPROVED** [review]

**Comment by Freeing3092** [comment]
> Looks good! If a user wants to search by just author or by just title though I think we would need to create separate methods?

'q' (title) seems to be a required query param for the google books api, so I don't believe it is possible to query solely by author. https://developers.google.com/books/docs/v1/using

If a user wanted to query just by title and not provide an author, I believe this should work as is with the current method and the `inauthor` query param as an empty string. Depending on the shape of what FE sends to this API call, there may be some additional logic required in the Facade, but it would probably be easiest if the FE sends both a title and an author in all cases (even if the author is an empty string).

**Pull request merged**
